import { PrismaClient } from '@prisma/client';
import { logger } from '../../src/shared/utils/logger';

const prisma = new PrismaClient();

export async function seedIntegrationProviders() {
  logger.info('🌐 Seeding integration providers...');

  const providers = [
    // Job Boards
    {
      name: 'LinkedIn Jobs',
      type: 'JOB_BOARD' as const,
      description: 'LinkedIn Jobs platform for posting and sourcing candidates',
      logoUrl: 'https://example.com/linkedin-logo.png',
      websiteUrl: 'https://linkedin.com/jobs',
      apiEndpoint: 'https://api.linkedin.com/v2',
      apiVersion: 'v2',
      authType: 'oauth',
      authConfig: {
        scopes: ['r_liteprofile', 'r_emailaddress', 'w_member_social'],
        redirectUri: 'https://api.teamcast.com/oauth/linkedin/callback',
      },
      supportsJobImport: true,
      supportsJobPublish: true,
      supportsCandidateImport: true,
      supportsCandidatePush: false,
      supportsPipelineUpdate: false,
      rateLimitPerMinute: 100,
      rateLimitPerHour: 5000,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['professional', 'tech', 'corporate'],
        regions: ['global'],
        languages: ['en', 'es', 'fr', 'de', 'pt'],
      },
    },
    {
      name: 'Indeed',
      type: 'JOB_BOARD' as const,
      description: 'Indeed job board for posting and sourcing candidates',
      logoUrl: 'https://example.com/indeed-logo.png',
      websiteUrl: 'https://indeed.com',
      apiEndpoint: 'https://api.indeed.com',
      apiVersion: 'v1',
      authType: 'api_key',
      authConfig: {
        requiresPublisherId: true,
        requiresJobId: true,
      },
      supportsJobImport: true,
      supportsJobPublish: true,
      supportsCandidateImport: true,
      supportsCandidatePush: false,
      supportsPipelineUpdate: false,
      rateLimitPerMinute: 60,
      rateLimitPerHour: 1000,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['general', 'tech', 'retail', 'healthcare'],
        regions: ['global'],
        languages: ['en', 'es', 'fr', 'de', 'pt', 'it'],
      },
    },
    {
      name: 'Glassdoor',
      type: 'JOB_BOARD' as const,
      description: 'Glassdoor job board with company reviews',
      logoUrl: 'https://example.com/glassdoor-logo.png',
      websiteUrl: 'https://glassdoor.com',
      apiEndpoint: 'https://api.glassdoor.com',
      apiVersion: 'v1',
      authType: 'api_key',
      authConfig: {
        requiresPartnerId: true,
        requiresUserIp: true,
      },
      supportsJobImport: true,
      supportsJobPublish: true,
      supportsCandidateImport: true,
      supportsCandidatePush: false,
      supportsPipelineUpdate: false,
      rateLimitPerMinute: 30,
      rateLimitPerHour: 500,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['professional', 'reviews', 'salary'],
        regions: ['global'],
        languages: ['en'],
      },
    },
    {
      name: 'Monster',
      type: 'JOB_BOARD' as const,
      description: 'Monster job board for posting and sourcing candidates',
      logoUrl: 'https://example.com/monster-logo.png',
      websiteUrl: 'https://monster.com',
      apiEndpoint: 'https://api.monster.com',
      apiVersion: 'v1',
      authType: 'api_key',
      authConfig: {
        requiresClientId: true,
        requiresClientSecret: true,
      },
      supportsJobImport: true,
      supportsJobPublish: true,
      supportsCandidateImport: true,
      supportsCandidatePush: false,
      supportsPipelineUpdate: false,
      rateLimitPerMinute: 50,
      rateLimitPerHour: 2000,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['general', 'tech', 'finance'],
        regions: ['global'],
        languages: ['en', 'es', 'fr', 'de'],
      },
    },
    {
      name: 'ZipRecruiter',
      type: 'JOB_BOARD' as const,
      description: 'ZipRecruiter job board with AI-powered matching',
      logoUrl: 'https://example.com/ziprecruiter-logo.png',
      websiteUrl: 'https://ziprecruiter.com',
      apiEndpoint: 'https://api.ziprecruiter.com',
      apiVersion: 'v1',
      authType: 'api_key',
      authConfig: {
        requiresApiKey: true,
        supportsWebhooks: true,
      },
      supportsJobImport: true,
      supportsJobPublish: true,
      supportsCandidateImport: true,
      supportsCandidatePush: false,
      supportsPipelineUpdate: false,
      rateLimitPerMinute: 40,
      rateLimitPerHour: 1500,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['ai-powered', 'general', 'tech'],
        regions: ['global'],
        languages: ['en'],
      },
    },

    // ATS Systems
    {
      name: 'Workday',
      type: 'ATS' as const,
      description: 'Workday Human Capital Management and ATS',
      logoUrl: 'https://example.com/workday-logo.png',
      websiteUrl: 'https://workday.com',
      apiEndpoint: 'https://api.workday.com',
      apiVersion: 'v1',
      authType: 'oauth',
      authConfig: {
        scopes: ['recruiting', 'candidates', 'jobs'],
        redirectUri: 'https://api.teamcast.com/oauth/workday/callback',
      },
      supportsJobImport: true,
      supportsJobPublish: false,
      supportsCandidateImport: true,
      supportsCandidatePush: true,
      supportsPipelineUpdate: true,
      rateLimitPerMinute: 20,
      rateLimitPerHour: 500,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['enterprise', 'hcm', 'ats'],
        regions: ['global'],
        languages: ['en', 'es', 'fr', 'de', 'ja'],
      },
    },
    {
      name: 'BambooHR',
      type: 'ATS' as const,
      description: 'BambooHR HRIS and ATS for small to medium businesses',
      logoUrl: 'https://example.com/bamboohr-logo.png',
      websiteUrl: 'https://bamboohr.com',
      apiEndpoint: 'https://api.bamboohr.com',
      apiVersion: 'v1',
      authType: 'api_key',
      authConfig: {
        requiresSubdomain: true,
        requiresApiKey: true,
      },
      supportsJobImport: true,
      supportsJobPublish: false,
      supportsCandidateImport: true,
      supportsCandidatePush: true,
      supportsPipelineUpdate: true,
      rateLimitPerMinute: 30,
      rateLimitPerHour: 1000,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['smb', 'hr', 'ats'],
        regions: ['global'],
        languages: ['en', 'es', 'fr'],
      },
    },
    {
      name: 'Greenhouse',
      type: 'ATS' as const,
      description: 'Greenhouse ATS for modern recruiting',
      logoUrl: 'https://example.com/greenhouse-logo.png',
      websiteUrl: 'https://greenhouse.io',
      apiEndpoint: 'https://harvest.greenhouse.io/v1',
      apiVersion: 'v1',
      authType: 'api_key',
      authConfig: {
        requiresApiKey: true,
        supportsWebhooks: true,
      },
      supportsJobImport: true,
      supportsJobPublish: false,
      supportsCandidateImport: true,
      supportsCandidatePush: true,
      supportsPipelineUpdate: true,
      rateLimitPerMinute: 25,
      rateLimitPerHour: 800,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['modern', 'tech', 'ats'],
        regions: ['global'],
        languages: ['en'],
      },
    },
    {
      name: 'Lever',
      type: 'ATS' as const,
      description: 'Lever ATS for collaborative hiring',
      logoUrl: 'https://example.com/lever-logo.png',
      websiteUrl: 'https://lever.co',
      apiEndpoint: 'https://api.lever.co/v1',
      apiVersion: 'v1',
      authType: 'api_key',
      authConfig: {
        requiresApiKey: true,
        supportsWebhooks: true,
      },
      supportsJobImport: true,
      supportsJobPublish: false,
      supportsCandidateImport: true,
      supportsCandidatePush: true,
      supportsPipelineUpdate: true,
      rateLimitPerMinute: 20,
      rateLimitPerHour: 600,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['collaborative', 'modern', 'ats'],
        regions: ['global'],
        languages: ['en'],
      },
    },
    {
      name: 'Jobvite',
      type: 'ATS' as const,
      description: 'Jobvite ATS with social recruiting features',
      logoUrl: 'https://example.com/jobvite-logo.png',
      websiteUrl: 'https://jobvite.com',
      apiEndpoint: 'https://api.jobvite.com',
      apiVersion: 'v1',
      authType: 'oauth',
      authConfig: {
        scopes: ['candidates', 'jobs', 'analytics'],
        redirectUri: 'https://api.teamcast.com/oauth/jobvite/callback',
      },
      supportsJobImport: true,
      supportsJobPublish: false,
      supportsCandidateImport: true,
      supportsCandidatePush: true,
      supportsPipelineUpdate: true,
      rateLimitPerMinute: 15,
      rateLimitPerHour: 400,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['social', 'recruiting', 'ats'],
        regions: ['global'],
        languages: ['en'],
      },
    },
    {
      name: 'iCIMS',
      type: 'ATS' as const,
      description: 'iCIMS Talent Cloud ATS',
      logoUrl: 'https://example.com/icims-logo.png',
      websiteUrl: 'https://icims.com',
      apiEndpoint: 'https://api.icims.com',
      apiVersion: 'v1',
      authType: 'api_key',
      authConfig: {
        requiresCustomerId: true,
        requiresApiKey: true,
        requiresApiSecret: true,
      },
      supportsJobImport: true,
      supportsJobPublish: false,
      supportsCandidateImport: true,
      supportsCandidatePush: true,
      supportsPipelineUpdate: true,
      rateLimitPerMinute: 10,
      rateLimitPerHour: 300,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['enterprise', 'talent-cloud', 'ats'],
        regions: ['global'],
        languages: ['en', 'es', 'fr'],
      },
    },
    {
      name: 'Workable',
      type: 'ATS' as const,
      description: 'Workable ATS for modern recruiting and hiring',
      logoUrl: 'https://example.com/workable-logo.png',
      websiteUrl: 'https://workable.com',
      apiEndpoint: 'https://{subdomain}.workable.com/spi/v3',
      apiVersion: 'v3',
      authType: 'api_key',
      authConfig: {
        requiresSubdomain: true,
        requiresApiKey: true,
        supportsWebhooks: true,
        baseUrl: 'https://{subdomain}.workable.com',
      },
      supportsJobImport: true,
      supportsJobPublish: false,
      supportsCandidateImport: true,
      supportsCandidatePush: true,
      supportsPipelineUpdate: true,
      rateLimitPerMinute: 30,
      rateLimitPerHour: 1000,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['modern', 'recruiting', 'ats'],
        regions: ['global'],
        languages: ['en', 'es', 'fr', 'de', 'it', 'pt'],
      },
    },
    {
      name: 'Excel Upload',
      type: 'ATS' as const,
      description: 'Excel file upload for candidate import',
      logoUrl:
        'https://upload.wikimedia.org/wikipedia/commons/3/34/Microsoft_Office_Excel_%282019%E2%80%93present%29.svg',
      websiteUrl: 'https://excel.cloud.microsoft/en-gb/',
      apiEndpoint: null,
      apiVersion: null,
      authType: 'file_upload',
      authConfig: {
        supportedFormats: ['xlsx', 'xls', 'csv'],
        maxFileSize: '10MB',
        requiresTemplate: true,
      },
      supportsJobImport: false,
      supportsJobPublish: false,
      supportsCandidateImport: true,
      supportsCandidatePush: false,
      supportsPipelineUpdate: false,
      rateLimitPerMinute: 10,
      rateLimitPerHour: 100,
      isActive: true,
      isVerified: true,
      metadata: {
        categories: ['file-upload', 'candidate-import', 'ats'],
        regions: ['global'],
        languages: ['en'],
      },
    },
  ];

  for (const provider of providers) {
    await prisma.integration_provider.upsert({
      where: { name: provider.name },
      update: provider,
      create: provider,
    });
  }

  logger.info(`✅ Seeded ${providers.length} integration providers`);
}

// Run the seed function if this file is executed directly
if (require.main === module) {
  seedIntegrationProviders()
    .catch((error) => {
      logger.error('❌ Error seeding integration providers:', error);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
