export enum ErrorCode {
  // Authentication Errors (1xxx)
  UNAUTHORIZED = 'ERR_1001',
  INVALID_CREDENTIALS = 'ERR_1002',
  TOKEN_EXPIRED = 'ERR_1003',
  INVALID_TOKEN = 'ERR_1004',
  USER_NOT_ACTIVE = 'ERR_1005',
  EMAIL_NOT_VERIFIED = 'ERR_1006',

  // Authorization Errors (2xxx)
  FORBIDDEN = 'ERR_2001',
  INSUFFICIENT_PERMISSIONS = 'ERR_2002',

  // Validation Errors (3xxx)
  INVALID_INPUT = 'ERR_3001',
  MISSING_REQUIRED_FIELD = 'ERR_3002',
  INVALID_EMAIL = 'ERR_3003',
  INVALID_PASSWORD = 'ERR_3004',
  INVALID_REQUEST = 'ERR_3005',
  VALIDATION_ERROR = 'ERR_3006',
  INVITATION_EXPIRED = 'ERR_3007',
  PASSWORD_CHANGE_FAILED = 'ERR_3008',

  // Resource Errors (4xxx)
  NOT_FOUND = 'ERR_4001',
  ALREADY_EXISTS = 'ERR_4002',
  CONFLICT = 'ERR_4003',
  EMAIL_ALREADY_EXISTS = 'ERR_4004',

  // Database Errors (5xxx)
  DB_ERROR = 'ERR_5001',
  DB_CONNECTION_ERROR = 'ERR_5002',
  DB_QUERY_ERROR = 'ERR_5003',

  // Server Errors (6xxx)
  INTERNAL_SERVER_ERROR = 'ERR_6001',
  SERVICE_UNAVAILABLE = 'ERR_6002',
  EXTERNAL_SERVICE_ERROR = 'ERR_6003',
  NOT_IMPLEMENTED = 'ERR_6004',
  FILE_NOT_FOUND = 'ERR_6005',
  STORAGE_ERROR = 'ERR_6006',

  // Subscription Errors (7xxx)
  SUBSCRIPTION_REQUIRED = 'ERR_7001',
  SUBSCRIPTION_LIMIT_REACHED = 'ERR_7002',
  SUBSCRIPTION_EXPIRED = 'ERR_7003',
  SUBSCRIPTION_NOT_FOUND = 'ERR_7004',
  SUBSCRIPTION_ALREADY_EXISTS = 'ERR_7005',
  SUBSCRIPTION_INVALID = 'ERR_7006',

  // Payment Errors (8xxx)
  PAYMENT_GATEWAY_ERROR = 'ERR_8001',
  PAYMENT_METHOD_ERROR = 'ERR_8002',
  PAYMENT_METHOD_NOT_FOUND = 'ERR_8003',
  PAYMENT_METHOD_ALREADY_EXISTS = 'ERR_8004',
  PAYMENT_METHOD_INVALID = 'ERR_8005',
  PAYMENT_METHOD_EXPIRED = 'ERR_8006',
  PAYMENT_METHOD_DECLINED = 'ERR_8007',

  // Job Application Errors (9xxx)
  JOB_APPLICATION_ALREADY_EXISTS = 'ERR_9001',
  JOB_APPLICATION_NOT_FOUND = 'ERR_9002',
  JOB_APPLICATION_STATUS_INVALID = 'ERR_9003',
  JOB_APPLICATION_RESUME_UPLOAD_ERROR = 'ERR_9004',
  JOB_APPLICATION_COVER_LETTER_UPLOAD_ERROR = 'ERR_9005',
  INVALID_JOB_APPLICATION_STATUS_TRANSITION = 'ERR_9006',
  AI_ASSESSMENT_NOT_FOUND = 'ERR_9007',
  AI_ASSESSMENT_INVALID = 'ERR_9008',
  AI_ASSESSMENT_NOT_COMPLETED = 'ERR_9009',
  ASSESSMENT_INVITATION_EXPIRED = 'ERR_9010',
  JOB_INVITE_NOT_ACCEPTED = 'ERR_9011',

  // Candidate Errors (10xxx)
  CANDIDATE_ID_REQUIRED = 'ERR_10001',
  RESUME_ALREADY_EXISTS = 'ERR_10002',
  CANDIDATE_NOT_FOUND = 'ERR_10003',
  RESUME_NOT_FOUND = 'ERR_10004',
  EXPERIENCE_NOT_FOUND = 'ERR_10005',
  CERTIFICATION_NOT_FOUND = 'ERR_10006',
  EDUCATION_NOT_FOUND = 'ERR_10007',
  PROJECT_NOT_FOUND = 'ERR_10008',
  USER_TYPE_CONFLICT = 'ERR_10009',

  // Job Posting Errors (11xxx)
  JOB_POSTING_NOT_FOUND = 'ERR_11001',
  JOB_POSTING_ALREADY_EXISTS = 'ERR_11002',
  JOB_POSTING_STATUS_INVALID = 'ERR_11003',
  JOB_POSTING_RESUME_UPLOAD_ERROR = 'ERR_11004',
  JOB_POSTING_COVER_LETTER_UPLOAD_ERROR = 'ERR_11005',
  INVALID_JOB_POSTING_STATUS_TRANSITION = 'ERR_11006',
  JD_PARSING_TASK_NOT_COMPLETED_OR_FAILED = 'ERR_11007',
  JD_PARSING_TASK_NOT_PENDING_OR_PROCESSING = 'ERR_11008',
  JD_PARSING_TASK_ALREADY_EXISTS = 'ERR_11009',
  JD_PARSING_TASK_NOT_FOUND = 'ERR_11010',
  JD_PARSING_TASK_NOT_COMPLETED = 'ERR_11011',

  // Candidate Recommendation Errors (12xxx)
  CANDIDATE_RECOMMENDATION_NOT_FOUND = 'ERR_12001',
  CANDIDATE_INVALID_RECOMMENDATION_FILTER = 'ERR_12002',

  // Candidate Recommendation Feedback Errors (13xxx)
  CANDIDATE_RECOMMENDATION_FEEDBACK_NOT_FOUND = 'ERR_13001',
  CANDIDATE_INVALID_RECOMMENDATION_FEEDBACK_TYPE = 'ERR_13002',
  CANDIDATE_RECOMMENDATION_FEEDBACK_ALREADY_EXISTS = 'ERR_13003',

  // Job Posting
  JOB_RECOMMENDATION_NOT_FOUND = 'ERR_13004',
  JOB_RECOMMENDATION_FEEDBACK_NOT_FOUND = 'ERR_13005',

  // Client User Errors (14xxx)
  CLIENT_USER_ID_REQUIRED = 'ERR_14001',

  // Partner User Errors (15xxx)
  PARTNER_ID_REQUIRED = 'ERR_15001',

  // New error codes
  PARSING_TASK_NOT_FOUND = 'ERR_15002',
  PARSING_TASK_IN_PROGRESS = 'ERR_15003',
  FILE_REQUIRED = 'ERR_15004',
  PARSING_TASK_NOT_COMPLETED = 'ERR_15005',
  PARSING_TASK_NOT_COMPLETED_OR_FAILED = 'ERR_15006',
  PARSING_TASK_NOT_PENDING_OR_PROCESSING = 'ERR_15007',
  INVALID_PARSING_MODE = 'ERR_15008',
  RESUME_PARSING_TASK_ALREADY_EXISTS = 'ERR_15009',

  // Resume Assessment Errors (16xxx)
  RESUME_ASSESSMENT_TASK_IN_PROGRESS = 'ERR_16001',
  RESUME_ASSESSMENT_TASK_NOT_FOUND = 'ERR_16002',
  RESUME_ASSESSMENT_TASK_NOT_COMPLETED = 'ERR_16003',
  RESUME_ASSESSMENT_TASK_NOT_COMPLETED_OR_FAILED = 'ERR_16004',
  RESUME_ASSESSMENT_TASK_NOT_PENDING_OR_PROCESSING = 'ERR_16005',

  RESUME_ASSESSMENT_NOT_FOUND = 'ERR_16006',
  RESUME_ASSESSMENT_INVALID = 'ERR_16007',
  RESUME_ASSESSMENT_NOT_COMPLETED = 'ERR_16008',
  RESUME_ASSESSMENT_NOT_COMPLETED_OR_FAILED = 'ERR_16009',
  RESUME_ASSESSMENT_NOT_PENDING_OR_PROCESSING = 'ERR_16010',
  RESUME_ASSESSMENT_TASK_ALREADY_EXISTS = 'ERR_16011',

  CANDIDATE_COMPLETION_PERCENTAGE_TOO_LOW = 'ERR_17001',

  // Onboarding Assessment Errors (18xxx)
  ONBOARDING_ASSESSMENT_ID_REQUIRED = 'ERR_18001',
  ONBOARDING_ASSESSMENT_TASK_ID_REQUIRED = 'ERR_18002',
  ONBOARDING_ASSESSMENT_TASK_NOT_FOUND = 'ERR_18003',
  ONBOARDING_ASSESSMENT_TASK_NOT_COMPLETED = 'ERR_18004',
  ONBOARDING_ASSESSMENT_TASK_NOT_COMPLETED_OR_FAILED = 'ERR_18005',
  ONBOARDING_ASSESSMENT_TASK_NOT_PENDING_OR_PROCESSING = 'ERR_18006',
  ONBOARDING_ASSESSMENT_INITIALIZE_TASK_NOT_CREATED = 'ERR_18007',
  ONBOARDING_ASSESSMENT_NOT_FOUND = 'ERR_18008',

  // Global Onboarding Assessment Settings Errors (19xxx)
  GLOBAL_ONBOARDING_ASSESSMENT_SETTINGS_NOT_FOUND = 'ERR_19001',
  GLOBAL_ONBOARDING_ASSESSMENT_SETTINGS_ALREADY_EXISTS = 'ERR_19002',

  // Onboarding Assessment Question Errors (20xxx)
  ONBOARDING_ASSESSMENT_QUESTION_NOT_FOUND = 'ERR_20001',
  ONBOARDING_ASSESSMENT_QUESTION_ALREADY_EXISTS = 'ERR_20002',
  ONBOARDING_ASSESSMENT_QUESTION_INVALID = 'ERR_20003',
  ONBOARDING_ASSESSMENT_QUESTION_NOT_COMPLETED = 'ERR_20004',
  ONBOARDING_ASSESSMENT_QUESTION_NOT_COMPLETED_OR_FAILED = 'ERR_20005',
  ONBOARDING_ASSESSMENT_QUESTION_NOT_PENDING_OR_PROCESSING = 'ERR_20006',
  ONBOARDING_ASSESSMENT_SECTION_NOT_FOUND = 'ERR_20007',
  ONBOARDING_ASSESSMENT_SECTION_ALREADY_EXISTS = 'ERR_20008',
  ONBOARDING_ASSESSMENT_SECTION_INVALID = 'ERR_20009',
  ONBOARDING_ASSESSMENT_SECTION_NOT_COMPLETED = 'ERR_20010',
  ONBOARDING_ASSESSMENT_SECTION_NOT_COMPLETED_OR_FAILED = 'ERR_20011',
  ONBOARDING_ASSESSMENT_SECTION_NOT_PENDING_OR_PROCESSING = 'ERR_20012',
  ONBOARDING_ASSESSMENT_PROGRESS_NOT_FOUND = 'ERR_20013',
  ONBOARDING_ASSESSMENT_COMPLETED_NO_MORE_QUESTIONS = 'ERR_20014',
  ONBOARDING_ASSESSMENT_VIDEO_ANALYSIS_NOT_FOUND = 'ERR_20015',

  // Assessment errors
  ASSESSMENT_NOT_READY = 'ERR_21001',
  ASSESSMENT_NOT_IN_PROGRESS = 'ERR_21002',
  NO_SECTIONS_FOUND = 'ERR_21003',
  NO_QUESTIONS_FOUND = 'ERR_21004',
  QUESTION_NOT_FOUND = 'ERR_21005',
  SECTION_NOT_FOUND = 'ERR_21006',

  // Candidate Assessment errors
  CANDIDATE_ASSESSMENT_NOT_IN_PROGRESS = 'ERR_22001',
  AI_ASSESSMENT_TASK_NOT_FOUND = 'ERR_22002',
  NO_NEXT_QUESTION_FOUND = 'ERR_22003',
  NO_NEXT_SECTION_FOUND = 'ERR_22004',
  ASSESSMENT_TASK_ALREADY_EXISTS = 'ERR_22005',
  ONBOARDING_ASSESSMENT_TASK_ALREADY_EXISTS = 'ERR_22006',

  // Candidate Assessment Stage errors
  CANDIDATE_ASSESSMENT_STAGE_NOT_IN_ASSESSMENT = 'ERR_23001',

  // Question errors
  ONBOARDING_ASSESSMENT_QUESTION_ALREADY_ANSWERED = 'ERR_24001',

  // OAuth Errors (30xxx)
  OAUTH_ACCOUNT_ALREADY_LINKED = 'ERR_30001',
  OAUTH_ACCOUNT_NOT_FOUND = 'ERR_30002',
  OAUTH_TOKEN_EXCHANGE_FAILED = 'ERR_30003',
  OAUTH_USER_INFO_FAILED = 'ERR_30004',
  OAUTH_AUTHENTICATION_FAILED = 'ERR_30005',

  // Job AI Assessment Errors (31xxx)
  JOB_AI_ASSESSMENT_NOT_FOUND = 'ERR_31001',
  JOB_AI_ASSESSMENT_INVALID = 'ERR_31002',
  JOB_AI_ASSESSMENT_NOT_COMPLETED = 'ERR_31003',
  JOB_AI_ASSESSMENT_NOT_COMPLETED_OR_FAILED = 'ERR_31004',
  JOB_AI_ASSESSMENT_NOT_PENDING_OR_PROCESSING = 'ERR_31005',
  JOB_AI_ASSESSMENT_TASK_ALREADY_EXISTS = 'ERR_31006',
  JOB_AI_ASSESSMENT_NOT_IN_PROGRESS = 'ERR_31007',
  JOB_AI_ASSESSMENT_NOT_IN_ASSESSMENT = 'ERR_31008',
  JOB_AI_ASSESSMENT_ID_REQUIRED = 'ERR_31009',
  JOB_AI_ASSESSMENT_TASK_ID_REQUIRED = 'ERR_31010',
  JOB_AI_ASSESSMENT_TASK_NOT_FOUND = 'ERR_31011',
  JOB_AI_ASSESSMENT_TASK_NOT_COMPLETED = 'ERR_31012',
  JOB_AI_ASSESSMENT_TASK_NOT_COMPLETED_OR_FAILED = 'ERR_31013',
  JOB_AI_ASSESSMENT_TASK_NOT_PENDING_OR_PROCESSING = 'ERR_31014',
  JOB_AI_ASSESSMENT_QUESTION_ALREADY_ANSWERED = 'ERR_31015',
  JOB_AI_ASSESSMENT_QUESTION_NOT_FOUND = 'ERR_31016',
  JOB_AI_ASSESSMENT_SECTION_NOT_FOUND = 'ERR_31017',
  JOB_AI_ASSESSMENT_SECTION_ALREADY_EXISTS = 'ERR_31018',
  JOB_AI_ASSESSMENT_SECTION_INVALID = 'ERR_31019',
  JOB_AI_ASSESSMENT_SECTION_NOT_COMPLETED = 'ERR_31020',
  JOB_AI_ASSESSMENT_SECTION_NOT_COMPLETED_OR_FAILED = 'ERR_31021',
  JOB_AI_ASSESSMENT_SECTION_NOT_PENDING_OR_PROCESSING = 'ERR_31022',
  JOB_AI_ASSESSMENT_VIDEO_ANALYSIS_NOT_FOUND = 'ERR_31023',
  JOB_POSTING_ASSESSMENT_TASK_NOT_FOUND = 'ERR_31024',
  JOB_POSTING_ASSESSMENT_TASK_NOT_COMPLETED = 'ERR_31025',
  JOB_POSTING_ASSESSMENT_TASK_NOT_COMPLETED_OR_FAILED = 'ERR_31026',
  JOB_POSTING_ASSESSMENT_TASK_NOT_PENDING_OR_PROCESSING = 'ERR_31027',
  JOB_POSTING_ASSESSMENT_TASK_ALREADY_EXISTS = 'ERR_31028',
  JOB_POSTING_ASSESSMENT_TASK_NOT_IN_PROGRESS = 'ERR_31029',
  JOB_POSTING_ASSESSMENT_TASK_NOT_IN_ASSESSMENT = 'ERR_31030',
  JOB_POSTING_ASSESSMENT_TASK_ID_REQUIRED = 'ERR_31031',
  JOB_POSTING_ASSESSMENT_NOT_FOUND = 'ERR_31032',
  JOB_POSTING_ASSESSMENT_NOT_IN_PROGRESS = 'ERR_31033',
  JOB_POSTING_ASSESSMENT_NOT_IN_ASSESSMENT = 'ERR_31034',
  JOB_POSTING_ASSESSMENT_ID_REQUIRED = 'ERR_31035',
  JOB_POSTING_ASSESSMENT_NOT_COMPLETED = 'ERR_31036',
  JOB_POSTING_ASSESSMENT_NOT_COMPLETED_OR_FAILED = 'ERR_31037',
  JOB_POSTING_ASSESSMENT_NOT_PENDING_OR_PROCESSING = 'ERR_31038',
  JOB_POSTING_ASSESSMENT_VALIDATION_FAILED = 'ERR_31039',

  // Integration Errors (32xxx)
  INTEGRATION_FEATURE_NOT_SUPPORTED = 'ERR_32001',
  INTEGRATION_PROVIDER_NOT_FOUND = 'ERR_32002',
  INTEGRATION_CONNECTION_FAILED = 'ERR_32003',
  INTEGRATION_SYNC_FAILED = 'ERR_32004',
  INTEGRATION_CREDENTIALS_INVALID = 'ERR_32005',

  NOTIFICATION_ERROR = 'NOTIFICATION_ERROR',
}
